foss-for-synopsys-dwc-arc-processors/embarc_mli

build/rules.mk, examples/example_cifar10_caffe/Makefile, examples/example_har_smartphone/Makefile
Hi, this branch contains few corrections required for GNU examples (can be squashed together in one commit).
=> Fix quoting for cifar10 gnu3

README.md, lib/gen/lutfx.py
LUT tables generator script + generators dir is mentioned in root Readme
=> LookUp tables generator script

include/api/mli_kernels_api.h, lib/src/kernels/common/mli_krn_fully_connected.h, lib/src/kernels/common/mli_krn_fully_connected_fx.cc, lib/src/private/mli_math.h
review https://ccollab01/ui#review:id=923068
=> implementation fully connected function with new datatypes

doc/documents/MLI_helpers/convert_tensor.rst
Please Rebase and remove branche afterward,
=> Fix parameter name in a table

doc/documents/MLI_helpers/get_basic_elem_size.rst
Please, rebase and delete branch afterward
=> Doc Fix: wrong prototype of function

Makefile
Please, merge by rebase and remove branch afterward
=> Fix makecall to platform agnostic alias

lib/src/kernels/convolution/mli_krn_conv2d_hwc_fx16.cc, lib/src/private/mli_prv_tensor.h
Signed-off-by: R. Hilkens <hilkens@synopsys.com>
=> [memory stride] small cleanup/fixes

lib/src/kernels/common/mli_krn_fully_connected_fx.cc, lib/src/private/src/mli_check.cc
- FC checking in release is removed
- Fix continuity condition for memstrid+rank only
- Consistence for mem stride checking/logging with other checks
=> Update memstride checking logic + FC checking in release

include/api/mli_helpers_api.h, lib/src/private/mli_prv_tensor.h
[Change]
- small fix for mli_prv_get_conv2d_weights_tensor_1hwn
- asserts added
- more code clearity
Signed-off-by: R. Hilkens <hilkens@synopsys.com>
=> [memory strides] small cleanup/fixes 2

lib/make/makefile, lib/src/kernels/convolution/mli_krn_conv2d_chw.h, lib/src/private/mli_debug.h, lib/src/private/mli_math.h, lib/src/private/mli_prv_dsp.h, lib/src/private/mli_prv_load_store.h
Signed-off-by: R. Hilkens <hilkens@synopsys.com>
=> [build] Turn on -Werror and -Wall for the library build

lib/src/move/mli_mov_api.c
Signed-off-by: R. Hilkens <hilkens@synopsys.com>
=> [build] avoid warning -Wmissing-braces

lib/src/bricks/impl/mli_krn_reduce_max2d_dsp.h, lib/src/bricks/mli_krn_reduce_max2d.h, lib/src/kernels/pooling/mli_krn_maxpool_hwc.h, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_sa8.cc
- Fix function check bug
- Maxpool code cleanup
=> [Maxpool] Maxpool Bug Fix and code cleanup

CMakeLists.txt, cmake/settings.cmake, examples/CMakeLists.txt, examples/hello_world/CMakeLists.txt, examples/hello_world/main.cpp, examples/hello_world/make/Makefile, lib/CMakeLists.txt, lib/mli_lib.cmake, lib/src/pal/ref/mli_math.h
[Change]
- introduce CMAKE build for MLI
- allows to compile on MSVC (X86 Windows),
GCC/LLVM (X86 Linux) and MWDT.
=> [cmake build]

lib/make/makefile, lib/mli_lib.cmake, lib/src/bricks/impl/mli_krn_dotprod_ref.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/kernels/common/mli_krn_fully_connected_stub_fx.cc, lib/src/private/mli_prv_layout.h, lib/src/private/src/mli_prv_activation_lut.cc
[Change]
- add stub for fully_connected for VPX and X86 compilations
- add new files to build targets
=> [build builds]

include/api/mli_kernels_api.h, include/mli_types.h, lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_lut_ref.h, lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h, lib/src/kernels/transform/mli_krn_sigm_fx.cc, lib/src/kernels/transform/mli_krn_softmax.h, lib/src/kernels/transform/mli_krn_softmax_decl.h, lib/src/kernels/transform/mli_krn_softmax_fx.cc, lib/src/kernels/transform/mli_krn_tanh_fx.cc, lib/src/pal/dsp/mli_math.h, lib/src/private/mli_check.h, lib/src/private/mli_private_types.h, lib/src/private/mli_prv_activation_lut.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc, lib/src/private/src/mli_prv_activation_lut.cc
Add reference code for softmax fx16 kernel
=> [Softmax] Add reference code for softmax fx16 kernel

lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_lut_ref.h, lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/bricks/mli_prv_lut.h, lib/src/bricks/mli_prv_lut_decl.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/mli_krn_softmax.h, lib/src/kernels/transform/mli_krn_softmax_decl.h, lib/src/kernels/transform/mli_krn_softmax_fx.cc, lib/src/private/mli_check.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc, lib/src/private/src/mli_prv_activation_lut.cc
Add softmax sa8 reference code.
=> [Softmax] Add softmax sa8 reference code.

lib/src/bricks/mli_prv_lut.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h
fix build error EM/HS missing lut_activation function declration
=> [Softmax] fix build error EM/HS missing lut_activation function declration

examples/auxiliary/tensor_transform.c, examples/auxiliary/tests_aux.c, include/api/mli_helpers_api.h, include/mli_types.h, lib/src/bricks/impl/mli_prv_quant_dsp.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/helpers/src/mli_helpers.cc, lib/src/kernels/convolution/mli_krn_depthwise_conv2d_hwcn.cc, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/mli_krn_sigm_fx.cc, lib/src/kernels/transform/mli_krn_tanh_fx.cc, lib/src/pal/vdsp/mli_math.h, lib/src/pal/vdsp/mli_prv_load_store.h, lib/src/private/mli_check.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc
Change the scale value to 16bit and add per axis fractional bits
=> Interface update for asym datatypes

include/mli_types.h, lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_quant_dsp.h, lib/src/bricks/mli_prv_lut.h, lib/src/bricks/mli_prv_lut_decl.h, lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/mli_krn_softmax.h, lib/src/pal/dsp/mli_math.h, lib/src/private/mli_private_types.h, lib/src/private/mli_prv_tensor.h
- Refactoring Reference code.
- Adding Generic APIs.
- Adding DSP Version for Softmax and Activation LUT for Sigm/Tanh.
=> Dsp softmax

lib/mli_lib.cmake, lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_quant_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h, lib/src/kernels/transform/impl/mli_krn_relu_ref.h, lib/src/kernels/transform/impl/mli_krn_relu_vdsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/mli_krn_leaky_relu_fx.cc, lib/src/kernels/transform/mli_krn_prelu.h, lib/src/kernels/transform/mli_krn_prelu_decl.h, lib/src/kernels/transform/mli_krn_relu.h, lib/src/kernels/transform/mli_krn_relu_decl.h, lib/src/pal/dsp/mli_math.h, lib/src/pal/ref/mli_math.h, lib/src/pal/ref/mli_prv_load_store.h, lib/src/pal/vdsp/mli_math.h, lib/src/private/src/mli_check.cc
- Add generic REF implementation for Leaky/Parametric RELU that is used with REF/DSP/VDSP
- update generic REF implementation for RELU to be used with REF/DSP/VDSP.
=> Fx leaky relu

include/api/mli_kernels_api.h, lib/src/kernels/common/mli_krn_common.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_dsp.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/kernels/eltwise/mli_krn_eltwise.h, lib/src/kernels/eltwise/mli_krn_eltwise_add_fx.cc, lib/src/kernels/eltwise/mli_krn_eltwise_decl.h, lib/src/kernels/eltwise/mli_krn_eltwise_max_fx.cc, lib/src/kernels/eltwise/mli_krn_eltwise_min_fx.cc, lib/src/kernels/eltwise/mli_krn_eltwise_mul_fx.cc, lib/src/kernels/eltwise/mli_krn_eltwise_sub_fx.cc, lib/src/pal/dsp/mli_math.h, lib/src/pal/mli_math.h, lib/src/pal/ref/mli_math.h, lib/src/private/mli_check.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc
adding eltwise sa8 reference code
=> [Eltwise] add eltwise sa8 reference code

lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_lut_decl.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h, lib/src/kernels/transform/mli_krn_softmax.h, lib/src/pal/vdsp/arc_vector_ext.h, lib/src/pal/vdsp/mli_math.h
=> Implement softmax sa8 for vdsp

include/api/mli_kernels_api.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/mli_prv_quant.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/mli_krn_leaky_relu_fx.cc, lib/src/kernels/transform/mli_krn_prelu.h, lib/src/kernels/transform/mli_krn_prelu_decl.h, lib/src/pal/dsp/mli_math.h, lib/src/pal/ref/mli_math.h, lib/src/pal/vdsp/mli_math.h, lib/src/private/mli_check.h, lib/src/private/src/mli_check.cc
Reference implementation for SA8 Leaky RELU.
=> Sa8 leaky relu

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, user_tests/CMakeLists.txt, user_tests/make/Makefile, user_tests/test_components/test_crc32_calc.cc, user_tests/test_components/test_tensor_quantizer.cc, user_tests/tests/mli_krn_eltwise/tests_mli_krn_eltwise.cc, user_tests/tests/mli_krn_eltwise/vectors_mli_krn_eltwise.inc, user_tests/tests/mli_krn_softmax/tests_mli_krn_softmax.cc
adding support of eltwise basic testing
=> [user_tests] add support of eltwise basic testing

lib/src/pal/vdsp/mli_math.h
- Fix Rounding mode UP for VDSP Accumulator cast functions.
- Issues found during Leaky RELU FX16 UT
RID: 1111310
=> Rounding Mode VDSP

lib/src/bricks/impl/mli_krn_reduce_sum2d_vdsp.h, lib/src/kernels/pooling/mli_krn_avepool_hwc.h, lib/src/kernels/pooling/mli_krn_avepool_hwc_sa8.cc, lib/src/pal/dsp/mli_prv_dsp.h, lib/src/pal/ref/mli_prv_dsp.h, lib/src/pal/vdsp/mli_prv_dsp.h, user_tests/CMakeLists.txt, user_tests/make/Makefile, user_tests/tests/mli_krn_avepool/tests_mli_krn_avepool.cc, user_tests/tests/mli_krn_avepool/vectors_mli_krn_avepool.inc, user_tests/tests/mli_krn_maxpool/tests_mli_krn_maxpool.cc, user_tests/tests/mli_krn_maxpool/vectors_mli_krn_maxpool.inc
Adding User Basic Tests for Maxpool and Avepool.
Fixing avepool kernel to use Output Params provided by User.
=> Fix avepool

user_tests/CMakeLists.txt, user_tests/make/Makefile, user_tests/tests/mli_krn_relu/tests_mli_krn_relu.cc, user_tests/tests/mli_krn_relu/vectors_mli_krn_relu.inc
Adding user tests for RELU.
RID: 1112157
=> Relu user tests

user_tests/make/Makefile
RID: 1111945
ML_lib_daily_2_0/268/: PASS
=> Add command get_tests_list in user tests makefile

lib/src/bricks/impl/mli_krn_reduce_max2d_vdsp.h, lib/src/bricks/mli_krn_reduce_max2d_decl.h, lib/src/kernels/pooling/mli_krn_maxpool_hwc.h, lib/src/pal/vdsp/mli_math.h, lib/src/pal/vdsp/mli_prv_dsp.h
Add optimizations for maxpool vectorized version
RID: 1112031
=> [Maxpool] optimizations for maxpool vectorized version

user_tests/make/Makefile
CCID: 1117663
ML_lib_daily_2_0/334/: PASS
=> [user_tests] re-add kernels

lib/src/pal/vdsp/mli_math.h
- The add/sub templates were moved up to be usable in the mli_math_asr_rnd_fx templates.
- Adding (1 << (nbits - 1)) results in a negative shift if nbits is equal to zero. this issue is fixed by adding ((1 << nbits) >> 1).
=> Round up with shift right to converge in zero shifts

lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h, lib/src/kernels/transform/mli_krn_softmax.h, lib/src/kernels/transform/mli_krn_softmax_decl.h, lib/src/kernels/transform/mli_krn_softmax_fx.cc, lib/src/pal/vdsp/mli_math.h, lib/src/pal/vdsp/mli_prv_dsp.h
=> Softmax fx16 vdsp

lib/src/private/src/mli_check.cc
CCID: 1128525
ML_lib_test_nsim/15/: PASS
=> [mli_chk_inside_ccm] fix

lib/src/bricks/impl/mli_krn_reduce_max2d_vdsp.h, lib/src/kernels/pooling/mli_krn_maxpool_hwc.h
adding maxpool vpx optimizations
RID: 1126693
=> [Maxpool] Optimize vectorized maxpool for VPX

lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/mli_krn_leaky_relu_fx.cc, lib/src/kernels/transform/mli_krn_prelu.h, lib/src/kernels/transform/mli_krn_prelu_decl.h, lib/src/pal/dsp/mli_prv_dsp.h, lib/src/pal/ref/mli_prv_dsp.h, lib/src/pal/vdsp/mli_prv_dsp.h, user_tests/tests/mli_krn_prelu/tests_mli_krn_prelu.cc
- Adding Scale broadcasting feature to FX16 REF/DSP/VDSP.
- Remove leaky_relu FX16 implementation and use Generic PRELU
implementation instead.
RID:1130328
=> [prelu_opt]: Adding Scale Broadcasting Feature.

lib/src/kernels/convolution/impl/mli_krn_convolution_dsp.h, user_tests/tests/mli_krn_depthwise_conv/tests_mli_krn_depthwise_conv.cc
=> [dw_conv_bug_fix]: Fix Dil+Pad bug for SA8 DSP Version.

lib/src/bricks/impl/mli_krn_reduce_max2d_dsp.h, lib/src/bricks/impl/mli_krn_reduce_max2d_ref.h, lib/src/bricks/impl/mli_krn_reduce_max2d_vdsp.h, lib/src/bricks/mli_krn_reduce_max2d.h, lib/src/bricks/mli_krn_reduce_max2d_decl.h, lib/src/kernels/pooling/mli_krn_maxpool_hwc.h, lib/src/pal/vdsp/mli_math.h
- add maxpool kernel padding optimizations
- maxpool code restructure
RID: 1132061
=> [Maxpool] adding maxpool kernel padding optimizations

include/api/mli_helpers_api.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/helpers/mli_hlp_convert_tensor_decl.h, lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h, lib/src/helpers/src/mli_helpers.cc, lib/src/helpers/src/mli_hlp_convert_tensor.h, lib/src/pal/dsp/mli_math.h, lib/src/pal/mli_math.h, lib/src/pal/ref/mli_math.h, lib/src/pal/vdsp/mli_math.h, lib/src/private/mli_check.h, lib/src/private/src/mli_check.cc, user_tests/CMakeLists.txt, user_tests/make/Makefile, user_tests/test_components/test_tensor_quantizer.cc, user_tests/test_components/test_tensor_quantizer.h, user_tests/tests/mli_krn_hlp_convert_tensor/tests_mli_krn_hlp_convert_tensor.cc, user_tests/tests/mli_krn_hlp_convert_tensor/vectors_mli_krn_hlp_convert_tensor.inc
- Implemented kernels (for float and safx specific).
- Tests for kernel
- Checkers
RIDs: 1125214, 1125075, 1119454
=> [convert_tensor] Data Conversion kernel and tests (including safx ver.)

lib/src/kernels/transform/impl/mli_krn_l2_normalize_dsp.h, lib/src/kernels/transform/impl/mli_krn_l2_normalize_ref.h, lib/src/kernels/transform/impl/mli_krn_l2_normalize_vdsp.h, lib/src/kernels/transform/mli_krn_l2_normalize.h, lib/src/kernels/transform/mli_krn_l2_normalize_decl.h, lib/src/pal/vdsp/mli_math.h
- Adding FX16/SA8 VPX implementation of L2 Normalize Kernel.
RID: 1136503
=> [l2_norm_vec]: Adding L2 Normalize VPX implementation.

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/ref/mli_math.h, lib/src/pal/vdsp/arc_vector_ext.h, lib/src/pal/vdsp/mli_math.h
Vectorize eltwise max/min for fx16 and sa8.
=> Eltwise max min vec

lib/src/bricks/impl/mli_krn_dotprod_vdsp.h
=> extra unroll to speed up FC kernel

lib/src/move/mli_mov_api.cc
=> change mli_move_api into .cc file

lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/helpers/mli_hlp_convert_tensor_decl.h, lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h, lib/src/helpers/src/mli_helpers.cc, user_tests/tests/mli_krn_hlp_convert_tensor/tests_mli_krn_hlp_convert_tensor.cc
Refactored define_quant_params function. Add accumulator type change for convert_quantized_data. Clean up.
CCID: 1139617
=> [convert_tensor] Improvements and fixes.

lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/kernels/transform/impl/mli_krn_prelu_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h, lib/src/kernels/transform/mli_krn_leaky_relu_fx.cc, lib/src/kernels/transform/mli_krn_prelu.h, lib/src/kernels/transform/mli_krn_prelu_decl.h, lib/src/pal/vdsp/mli_math.h
RID: 1141508
ML_lib_test_nsim/187/: PASS
=> Prelu vpx sa8

lib/src/bricks/impl/mli_krn_reduce_sum2d_dsp.h, lib/src/bricks/impl/mli_krn_reduce_sum2d_ref.h, lib/src/bricks/impl/mli_krn_reduce_sum2d_vdsp.h, lib/src/bricks/impl/mli_prv_quant_dsp.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/mli_krn_reduce_sum2d_decl.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_dsp.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_ref.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_vdsp.h, lib/src/kernels/pooling/mli_krn_avepool_hwc.h, lib/src/kernels/pooling/mli_krn_avepool_hwc_decl.h, lib/src/kernels/pooling/mli_krn_avepool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_sa8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_sa8.cc, lib/src/kernels/pooling/mli_krn_pool_hwc.h, lib/src/pal/vdsp/mli_prv_dsp.h
RID: 1144720
ML_lib_test_nsim/210/: PASS
=> Avepool Optimization

include/api/mli_kernels_api.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/mli_prv_quant.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/kernels/common/impl/mli_krn_fully_connected_ref.h, lib/src/kernels/common/mli_krn_fully_connected.cc, lib/src/kernels/common/mli_krn_fully_connected_decl.h, user_tests/tests/mli_krn_fully_connected/tests_mli_krn_fully_connected.cc, user_tests/tests/mli_krn_fully_connected/vectors_mli_krn_fully_connected.inc
It also includes required user tests.
CCID: 1140123
ML_lib_test_nsim/212/: PASS
=> Fully Connected SA8 specialization for extended 

lib/src/bricks/impl/mli_krn_reduce_max2d_dsp.h, lib/src/bricks/impl/mli_krn_reduce_max2d_ref.h, lib/src/bricks/impl/mli_krn_reduce_max2d_vdsp.h, lib/src/bricks/impl/mli_krn_reduce_sum2d_vdsp.h, lib/src/bricks/mli_krn_reduce_max2d_decl.h, lib/src/bricks/mli_krn_reduce_sum2d_decl.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_dsp.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_ref.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_vdsp.h, lib/src/kernels/pooling/mli_krn_avepool_hwc_decl.h, lib/src/kernels/pooling/mli_krn_pool_hwc.h, lib/src/pal/vdsp/mli_math.h, lib/src/pal/vdsp/mli_prv_dsp.h
RID: 1148311
ML_lib_test_nsim/223/: PASS
=> Avepool opt

include/api/mli_kernels_api.h, include/mli_types.h, lib/mli_lib.cmake, lib/src/kernels/diverse/impl/mli_krn_argmax_ref.h, lib/src/kernels/diverse/mli_krn_argmax.cc, lib/src/kernels/diverse/mli_krn_argmax.h, lib/src/kernels/diverse/mli_krn_argmax_decl.h, lib/src/pal/dsp/mli_math.h, lib/src/private/mli_check.h, lib/src/private/src/mli_check.cc, user_tests/CMakeLists.txt, user_tests/make/Makefile, user_tests/test_components/test_tensor_quantizer.cc, user_tests/tests/mli_krn_argmax/tests_mli_krn_argmax.cc, user_tests/tests/mli_krn_argmax/vectors_mli_krn_argmax.inc
=> [argmax] Reference version of mli_krn_argmax (sa8 and fx16)

lib/src/bricks/impl/mli_prv_quant_vdsp.h
Review #1151634
ML_lib_test_nsim/277/: PASS
=> result_cast: shift left before mul_high

lib/src/private/mli_check.h, lib/src/private/src/mli_check.cc, user_tests/tests/mli_krn_rnn_dense/vectors_mli_krn_rnn_dense.inc
=> [rnn_dense] Updated input shape checker

lib/src/kernels/convolution/impl/mli_krn_transpose_conv_ref.h, user_tests/tests/mli_krn_transpose_conv2d/tests_mli_krn_transpose_conv2d.cc, user_tests/tests/mli_krn_transpose_conv2d/vectors_mli_krn_transpose_conv2d.inc
to make subtensor definition more straightforward and less buggy.
=> [Conv2d Transpose] Change order of weights patterns appliance 

user_tests/tests/mli_krn_conv2d/tests_mli_krn_conv2d.cc, user_tests/tests/mli_krn_fully_connected/tests_mli_krn_fully_connected.cc, user_tests/tests/mli_krn_transpose_conv2d/tests_mli_krn_transpose_conv2d.cc
RID: #1156762
ML_lib_test_nsim/369/: PASS
ML_lib_test_nsim_staging_integer_base/11/: PASS
=> Skip integer base overflown test cases

lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_lut_ref.h, lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/bricks/impl/mli_prv_quant_dsp.h, lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/pal/vdsp/mli_math.h, user_tests/tests/mli_krn_sigm/tests_mli_krn_sigm.cc, user_tests/tests/mli_krn_softmax/tests_mli_krn_softmax.cc
- optimize act_lut function
- add software pipelining to vpx activation lut function
- add new convert_sa8_fx16 function used in act_luc function
RID: 1153424
Deprecated RID: 1147994
=> [act_lut_opt] add activation lut function vpx optimizations

lib/src/kernels/convolution/impl/mli_krn_group_conv2d_vdsp.h, lib/src/kernels/convolution/mli_krn_group_conv2d.h, lib/src/kernels/convolution/mli_krn_group_conv2d_decl.h, lib/src/kernels/convolution/mli_krn_group_conv2d_hwcn.cc
- Add vectorized group convolution kernels
- Optimize group conv without padding
RID: 1158185
=> Vectorize Group Convolution kernels

lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/kernels/common/impl/mli_krn_fully_connected_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_group_conv2d_vdsp.h
RID: 1158782
ML_lib_test_nsim/405/: PASSED
=> conv2d optimizations

lib/src/kernels/convolution/impl/mli_krn_transpose_conv_ref.h
CCID: 1160437
ML_lib_test_nsim/474/: PASS
=> [Conv2d Transpose] Add Current Input area definition before calculations

README.md, examples/example_cifar10_caffe/README.md, examples/example_face_detect/README.md, examples/example_har_smartphone/README.md, examples/tutorial_cifar10_caffe_deployment/README.md
CCID: 1161633
ML_lib_test_nsim/491/: PASS
=> Fix link to documentation in Readme

lib/src/pal/ref/mli_math.h, user_tests/tests/mli_krn_group_conv2d/tests_mli_krn_group_conv2d.cc
RID: #1161774
ML_lib_test_nsim/489/: PASSED
=> Skip overflowed tests in group_conv2d for integer base

user_tests/tests/mli_krn_hlp_convert_tensor/vectors_mli_krn_hlp_convert_tensor.inc
=> [convert_tensor] Fixed bug for VPX optimized build.

lib/src/bricks/impl/mli_prv_quant_vdsp.h
=> [act_lut] fix -ve shift bug in act_lut function

lib/src/kernels/diverse/impl/mli_krn_permute_ref.h, lib/src/kernels/diverse/impl/mli_krn_permute_vdsp.h, lib/src/kernels/diverse/mli_krn_permute.h, lib/src/kernels/diverse/mli_krn_permute_decl.h, user_tests/make/Makefile
RID: 1160542
ML_lib_test_nsim/511: PASSED
=> Permute vectorization

lib/src/kernels/convolution/impl/mli_krn_transpose_conv_ref.h, lib/src/kernels/convolution/mli_krn_transpose_conv_decl.h
CCID: 1163551
ML_lib_test_nsim/557/: PASS
=> [Transp Conv2d] Proper definition of the input perception area

user_tests/tests/mli_krn_l2_normalize/vectors_mli_krn_l2_normalize.inc, user_tests/tests/mli_krn_permute/vectors_mli_krn_permute.inc, user_tests/tests/mli_krn_prelu/vectors_mli_krn_prelu.inc
=> Add copyrights in missed places

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/vdsp/mli_math.h
RID = #1164455
ML_lib_test_nsim/622/: PASSED
=> optimizations for eltwise_mul

include/api/mli_helpers_api.h, include/mli_types.h, lib/src/helpers/src/mli_helpers.cc, user_tests/test_components/test_quality_metrics.cc, user_tests/test_components/test_report.cc, user_tests/test_components/test_tensor_quantizer.cc, user_tests/tests/mli_krn_avepool/tests_mli_krn_avepool.cc, user_tests/tests/mli_krn_avepool/vectors_mli_krn_avepool.inc, user_tests/tests/mli_krn_conv2d/tests_mli_krn_conv2d.cc, user_tests/tests/mli_krn_conv2d/vectors_mli_krn_conv2d.inc, user_tests/tests/mli_krn_depthwise_conv/tests_mli_krn_depthwise_conv.cc, user_tests/tests/mli_krn_depthwise_conv/vectors_mli_krn_depthwise_conv.inc, user_tests/tests/mli_krn_fully_connected/tests_mli_krn_fully_connected.cc, user_tests/tests/mli_krn_fully_connected/vectors_mli_krn_fully_connected.inc
CCID: 1165895
ML_lib_test_nsim/621/: PASS
=> Unblock negative fractional bits for FX tensor type

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/vdsp/mli_math.h, user_tests/tests/mli_krn_eltwise/tests_mli_krn_eltwise.cc
Fix eltwise bug: mli eltwise addition incorrect by small amounts
RID: 1166013
=> [eltwise] fix eltwise add/sub accuracy

include/api/mli_kernels_api.h, include/mli_types.h, lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_lut_ref.h, lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/kernels/common/mli_krn_common.h, lib/src/kernels/common/mli_krn_lstm_fx.cc, lib/src/kernels/diverse/impl/mli_krn_argmax_ref.h, lib/src/kernels/transform/impl/mli_krn_l2_normalize_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h, lib/src/kernels/transform/mli_krn_l2_normalize.cc, lib/src/kernels/transform/mli_krn_l2_normalize_decl.h, lib/src/kernels/transform/mli_krn_sigm_fx.cc, lib/src/kernels/transform/mli_krn_softmax_decl.h, lib/src/kernels/transform/mli_krn_softmax_fx.cc, lib/src/kernels/transform/mli_krn_tanh_fx.cc, lib/src/private/mli_check.h, lib/src/private/mli_private_types.h, lib/src/private/src/mli_check.cc, lib/src/private/src/mli_prv_activation_lut.cc, user_tests/tests/mli_krn_argmax/tests_mli_krn_argmax.cc, user_tests/tests/mli_krn_l2_normalize/tests_mli_krn_l2_normalize.cc, user_tests/tests/mli_krn_relu/tests_mli_krn_relu.cc, user_tests/tests/mli_krn_sigm/tests_mli_krn_sigm.cc, user_tests/tests/mli_krn_softmax/tests_mli_krn_softmax.cc, user_tests/tests/mli_krn_tanh/tests_mli_krn_tanh.cc
RID: #1166021
ML_lib_test_nsim (internal branch)/629/: PASSED
=> Update transform functions API with lut parameter

cmake/settings.cmake
PASS: /ML_lib_test_xcam/206/
CCID: 1166393
=> [compile flag update]

lib/src/bricks/impl/mli_krn_dotprod_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_convolution_ref.h, lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_group_conv2d_ref.h, lib/src/kernels/convolution/impl/mli_krn_group_conv2d_vdsp.h, lib/src/private/mli_prv_tensor.h
RID: #1164289
ML_lib_test_nsim /637/: PASSED
=> conv2d and transpose_conv: optimizations for padding case

CODEOWNERS
=> Codeowners list update

examples/example_cifar10_caffe/CMakeLists.txt, examples/example_cifar10_caffe/README.md, examples/example_cifar10_caffe/cifar10_constants.h, examples/example_cifar10_caffe/cifar10_model.h, examples/example_cifar10_caffe/cifar10_model_hwcn.c, examples/example_cifar10_caffe/ml_api_cifar10_caffe_main.c
RID:#1168357
ML_lib_test_nsim /691/: PASSED
=> update cifar10 example to use lut for softmax

lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_ref.h, lib/src/pal/dsp/mli_math.h, lib/src/pal/vdsp/mli_math.h
RID: #1170501
ML_lib_test_xcam /246/: PASSED
=> Use intrinsic norm in vdsp and dsp

lib/src/kernels/convolution/impl/mli_krn_convolution_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/private/mli_prv_tensor.h
RID: 1170346
ML_lib_test_nsim /709/: PASSED
=> don't use void_p from memory container union - part 1

lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h
RID: 1171245
ML_lib_test_nsim /711/: PASSED
=> Fix asserts in convolution code

user_tests/tests/mli_krn_rnn_dense/tests_mli_krn_rnn_dense.cc
=> [rnn_dense] Input tensors initialization fix

lib/src/bricks/impl/mli_krn_rnn_dense_op_ref.h
=> [lstm] fix lstm build issue

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h
RID:#1173460
ML_lib_test_nsim /760/: PASSED
=> opt eltwise max/min sa8

lib/src/kernels/diverse/impl/mli_krn_permute_ref.h
RID: 1171987
ML_lib_test_nsim/797: PASSED
=> Fix selecting out dim for permute kernel

lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h
RID: 1175075
ML_lib_test_nsim/844/: PASS
=> opt eltwise max/min fx16

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/mli_krn_eltwise_decl.h, user_tests/CMakeLists.txt, user_tests/make/Makefile, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc
RID: #1174224
ML_lib_test_nsim/854/: PASS
=> Compile LSTM for datatype

include/mli_types.h, lib/src/private/src/mli_check.cc
RID: 1179417
ML_lib_test_nsim/901/: PASS
=> prepare interface for signed mem_stride

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/dsp/mli_math.h
ML_lib_test_nsim/939/: PASS
RID: #1179229
=> eltwise_mul sa8: use mac instead of preshift

lib/src/kernels/transform/impl/mli_krn_l2_normalize_vdsp.h
=> L2norm opt

lib/src/kernels/diverse/impl/mli_krn_argmax_ref.h, lib/src/private/src/mli_check.cc, user_tests/tests/mli_krn_argmax/tests_mli_krn_argmax.cc
=> update argmax for sa32 output

include/mli_types.h
=> Align lut structure interface with other public types

lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/kernels/eltwise/mli_krn_eltwise_decl.h
RID:1182476
ML_lib_test_nsim/1121:PASS
=> unroll eltwise max/min

doc/documents/mli_kernels/trans_leaky_relu.rst, doc/documents/mli_kernels/trans_param_relu.rst, lib/src/kernels/common/mli_krn_gru_cell.h, lib/src/kernels/common/mli_krn_lstm_cell.h, lib/src/private/src/mli_check.cc, user_tests/tests/mli_krn_avepool/tests_mli_krn_avepool.cc, user_tests/tests/mli_krn_avepool/vectors_mli_krn_avepool.inc, user_tests/tests/mli_krn_eltwise/tests_mli_krn_eltwise.cc, user_tests/tests/mli_krn_eltwise/vectors_mli_krn_eltwise.inc, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_gru_cell/vectors_mli_krn_gru_cell.inc, user_tests/tests/mli_krn_permute/tests_mli_krn_permute.cc, user_tests/tests/mli_krn_relu/tests_mli_krn_relu.cc, user_tests/tests/mli_krn_relu/vectors_mli_krn_relu.inc, user_tests/tests/mli_krn_sigm/tests_mli_krn_sigm.cc, user_tests/tests/mli_krn_sigm/vectors_mli_krn_sigm.inc, user_tests/tests/mli_krn_tanh/tests_mli_krn_tanh.cc, user_tests/tests/mli_krn_tanh/vectors_mli_krn_tanh.inc
- Add checkers for quant params
- add checking of Zero Point limitations for sa8.
- Adjust user tests for new requirements
=> Checking of quantization params:

examples/example_cifar10_caffe/CMakeLists.txt, examples/example_cifar10_caffe/Makefile, examples/example_cifar10_caffe/README.md
RID:1182476
ML_lib_test_nsim/1191:PASS
=> run cifar per data type

lib/src/private/src/mli_check.cc
=> Checkers unused constants fix

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/kernels/eltwise/mli_krn_eltwise_decl.h, lib/src/pal/dsp/mli_math.h, lib/src/pal/vdsp/mli_math.h, user_tests/tests/mli_krn_eltwise/tests_mli_krn_eltwise.cc, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc
RID: #1189590
ML_lib_test_nsim/1255/: PASS
=> negative_shift in eltwise_mul

user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc
RID: #1192104
ML_lib_test_nsim/1264/: PASS
=> revert user_test for vdsp

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/dsp/mli_math.h, lib/src/pal/ref/mli_math.h, lib/src/pal/vdsp/mli_math.h
RID: # 1192151
ML_lib_test_nsim/1268/: PASS
=> optimize eltwise mul preshift

lib/src/bricks/impl/mli_krn_rnn_dense_op_ref.h, lib/src/bricks/impl/mli_krn_rnn_dense_op_vdsp.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_quant_decl.h, lib/src/pal/vdsp/mli_prv_dsp.h
RID: #1192727
ML_lib_test_nsim/1275/: PASS
=> Fix SA8 dequantization

lib/src/kernels/transform/impl/mli_krn_l2_normalize_vdsp.h
RID: 1192780
ML_lib_test_nsim/1273/ : PASS
=> L2 norm opt

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, user_tests/tests/mli_krn_eltwise/tests_mli_krn_eltwise.cc
RID:1192129
ML_lib_test_nsim/1276:PASS
=> eltwise max/min negative shift

lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/mli_math.h, lib/src/pal/vdsp/mli_math.h
RID:1192877
ML_lib_test_nsim/1280:PASS
=> optimize max/min sa8

lib/mli_lib.cmake, lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h, lib/src/move/mli_mov_api.cc, lib/src/pal/mli_mem_info.h, lib/src/pal/vdsp/mli_prv_dsp.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc
=> [build] turn on Werror

user_tests/tests/mli_krn_conv2d/tests_mli_krn_conv2d.cc, user_tests/tests/mli_krn_depthwise_conv/tests_mli_krn_depthwise_conv.cc, user_tests/tests/mli_krn_fully_connected/tests_mli_krn_fully_connected.cc, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc
ML_lib_test_nsim/1299: PASSED
RID:1193873
=> Remove redundant stubs in user_tests

lib/src/move/mli_mov_api.cc
RID:1194369
ML_lib_test_nsim/1315:PASS
=> fix copy sa8 parameters in mov

lib/src/bricks/impl/mli_krn_rnn_dense_op_ref.h, lib/src/bricks/impl/mli_krn_rnn_dense_op_vdsp.h, lib/src/bricks/mli_krn_rnn_dense_op_decl.h, lib/src/kernels/common/mli_krn_gru_cell.h, lib/src/kernels/common/mli_krn_lstm_cell.h, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_gru_cell/vectors_mli_krn_gru_cell.inc, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc, user_tests/tests/mli_krn_lstm_cell/vectors_mli_krn_lstm_cell.inc, user_tests/tests/mli_krn_rnn_dense/tests_mli_krn_rnn_dense.cc, user_tests/tests/mli_krn_rnn_dense/vectors_mli_krn_rnn_dense.inc
=> Patch for rnn_dense_op scales iteration and memstride weights iteration

README.md
=> Readme 2 0 EA

lib/src/kernels/convolution/impl/mli_krn_group_conv2d_ref.h
=> Incorrect kernel choice fixed for group_conv2d with channel_multiplier

lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h
=> fix mul fx8 rnd bug

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, user_tests/tests/mli_krn_eltwise/tests_mli_krn_eltwise.cc, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc
RID:1196185
ML_lib_test_nsim/1389:PASS
=> negative shift support for eltwise add/sub

lib/src/kernels/diverse/impl/mli_krn_argmax_ref.h, lib/src/kernels/diverse/impl/mli_krn_argmax_vdsp.h, lib/src/kernels/diverse/mli_krn_argmax.h, lib/src/kernels/diverse/mli_krn_argmax_decl.h, lib/src/pal/vdsp/mli_math.h
ML_lib_test_nsim/1495: PASSED
RID: #1202144
=> Vectorize argmax search

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h
RID:1206904
ML_lib_test_nsim/1502:PASS
=> eltwise frac bits full range support

README.md, doc/documents/mli_kernels/convolution_grp.rst, doc/documents/mli_kernels/diverse_kernels_grp.rst, doc/documents/mli_kernels/pooling_grp.rst, doc/documents/mli_kernels/rec_fully_con_grp.rst, doc/documents/mli_kernels/trans_l2_norm.rst, doc/documents/mli_kernels/trans_param_relu.rst, doc/documents/mli_kernels/trans_sigmoid.rst, doc/documents/mli_kernels/trans_softmax.rst, doc/documents/mli_kernels/trans_tanh.rst, doc/documents/mli_kernels/transform_grp.rst
=> [Docs] Multiple minor fixes. Warning on devbranch in readme was returned

lib/src/kernels/pooling/impl/mli_krn_avepool_hwc_vdsp.h, lib/src/kernels/pooling/mli_krn_pool_hwc.h
RID:1210950
ML_lib_test_nsim/1521:PASS
=> Optimizations for pooling

lib/src/kernels/diverse/impl/mli_krn_permute_ref.h, lib/src/kernels/diverse/impl/mli_krn_permute_vdsp.h, lib/src/kernels/diverse/mli_krn_permute.h, lib/src/kernels/diverse/mli_krn_permute_decl.h, lib/src/pal/vdsp/mli_prv_load_store.h
RID:1211593
ML_lib_test_nsim/1536:PASS
=> Optimizations for permute kernel

lib/src/kernels/convolution/impl/mli_krn_group_conv2d_ref.h, lib/src/kernels/convolution/impl/mli_krn_transpose_conv_ref.h, lib/src/private/mli_prv_tensor.h
RID: #1211470
ML_lib_test_nsim/1541:PASS
=> Fix relu negative shift

lib/src/kernels/transform/impl/mli_krn_leaky_relu_ref.h, lib/src/kernels/transform/impl/mli_krn_leaky_relu_vdsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h
RID: 1213069
ML_lib_test_nsim/1545/: PASS
=> [prelu_fix]: Fix issue in functional prelu/leaky_relu ref/vdsp

lib/src/kernels/convolution/impl/mli_krn_group_conv2d_vdsp.h, lib/src/private/src/mli_check.cc
RID:1216138
ML_lib_test_nsim/1657:PASS
=> group conv2d supports per tensor quantization

lib/src/kernels/pooling/mli_krn_pool_hwc.h
RID:1216735
ML_lib_test_nsim/1658:PASS
=> Fix for pragma issue in x86 build

lib/src/pal/mli_mem_info.h, lib/src/private/mli_check.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc
RID:1202812
ML_lib_test_nsim/1666:PASS
=> [mli_check] Fixed mli_chk_create_subtensor.

lib/src/kernels/common/mli_krn_lstm_cell.h
RID:1214596
ML_lib_test_nsim/1706:PASS
=> [lstm_cell_opt] optimization FX data version

examples/auxiliary/examples_aux.c, examples/auxiliary/tensor_transform.c, examples/example_cifar10_caffe/cifar10_constants.h, examples/example_cifar10_caffe/cifar10_model.h, examples/example_cifar10_caffe/cifar10_model_hwcn.c, examples/example_cifar10_caffe/ml_api_cifar10_caffe_main.c, include/api/mli_helpers_api.h, lib/src/helpers/src/mli_helpers.cc, lib/src/move/mli_mov_api.cc, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc, user_tests/test_components/test_tensor_quantizer.cc, user_tests/test_components/test_tensor_quantizer.h, user_tests/tests/mli_hlp_convert_tensor/tests_mli_hlp_convert_tensor.cc, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_l2_normalize/tests_mli_krn_l2_normalize.cc, user_tests/tests/mli_krn_leaky_relu/tests_mli_krn_leaky_relu.cc, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc, user_tests/tests/mli_krn_prelu/tests_mli_krn_prelu.cc, user_tests/tests/mli_krn_relu/tests_mli_krn_relu.cc, user_tests/tests/mli_krn_sigm/tests_mli_krn_sigm.cc, user_tests/tests/mli_krn_softmax/tests_mli_krn_softmax.cc, user_tests/tests/mli_krn_tanh/tests_mli_krn_tanh.cc
RID:1216946
ML_lib_test_nsim/1720:PASS
=> remove use of void_p field in tensor memory union

lib/src/bricks/impl/mli_krn_dotprod_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h
RID:1218508
ML_lib_test_nsim/1741:PASS
=> optimizations for depthwise padding

lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h, lib/src/kernels/transform/mli_krn_prelu.h, lib/src/kernels/transform/mli_krn_prelu_decl.h
RID: 1219033
ML_lib_test_nsim/1764: PASS
=> PRELU FX16 opt

examples/auxiliary/tests_aux.c
RID:1219091
ML_lib_test_nsim/1762:PASS
=> remove void_p usage from test_aux

examples/example_cifar10_caffe/cifar10_constants.h, examples/example_cifar10_caffe/cifar10_model_hwcn.c, include/api/mli_helpers_api.h, lib/src/helpers/src/mli_helpers.cc, lib/src/kernels/common/mli_krn_gru_cell.h, lib/src/kernels/common/mli_krn_lstm_cell.h, lib/src/kernels/convolution/impl/mli_krn_convolution_ref.h, lib/src/kernels/convolution/impl/mli_krn_group_conv2d_ref.h, lib/src/private/mli_prv_tensor.h, lib/src/private/src/mli_check.cc, user_tests/test_components/test_tensor_quantizer.cc, user_tests/tests/mli_krn_conv2d/tests_mli_krn_conv2d.cc, user_tests/tests/mli_krn_conv2d/vectors_mli_krn_conv2d.inc, user_tests/tests/mli_krn_depthwise_conv/tests_mli_krn_depthwise_conv.cc, user_tests/tests/mli_krn_depthwise_conv/vectors_mli_krn_depthwise_conv.inc, user_tests/tests/mli_krn_group_conv2d/tests_mli_krn_group_conv2d.cc, user_tests/tests/mli_krn_group_conv2d/vectors_mli_krn_group_conv2d.inc
dilation factor needs to be > 0 
mem_stride is now mandatory
output shape needs to be set by the caller
RID:1216211
ML_lib_test_nsim/1779:PASS
=> simplify interface

doc/documents/mli_kernels/rec_gru.rst, doc/documents/mli_kernels/rec_lstm.rst, include/api/mli_kernels_api.h, lib/src/kernels/common/mli_krn_gru_cell.h, lib/src/kernels/common/mli_krn_lstm_cell.h, lib/src/private/src/mli_check.cc, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc
RID:1215397
ML_lib_test_nsim/1780:PASS
=> Avoiding "batch" term and replace it with sequence_length

lib/src/bricks/impl/mli_prv_quant_ref.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/pal/ref/mli_math.h, lib/src/pal/vdsp/mli_math.h, user_tests/tests/mli_krn_conv2d/tests_mli_krn_conv2d.cc, user_tests/tests/mli_krn_group_conv2d/tests_mli_krn_group_conv2d.cc, user_tests/tests/mli_krn_transpose_conv2d/tests_mli_krn_transpose_conv2d.cc
RID:1216167
ML_lib_test_nsim/1786:PASS
=> weight kernels fixes

lib/src/private/mli_prv_tensor.h
RID:1219894
ML_lib_test_nsim/1789:PASS
=> fix relu max_min overflow

doc/documents/mli_api_data/mli_tensor_data_struct.rst
CCID: 1220506
ML_lib_test_nsim/1839/: PASS
=> [Docs] Update scale_frac_bits field description

lib/src/bricks/impl/mli_krn_rnn_dense_op_vdsp.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/bricks/mli_prv_quant_decl.h
RID: #1223304
ML_lib_test_nsim/1858:PASS
=> clip shift right for RNN

lib/src/kernels/transform/impl/mli_krn_l2_normalize_ref.h, lib/src/kernels/transform/impl/mli_krn_l2_normalize_vdsp.h, lib/src/kernels/transform/mli_krn_l2_normalize.h, lib/src/kernels/transform/mli_krn_l2_normalize_decl.h
RID: 1224922
ML_lib_test_nsim/1855/ : PASS
=> [l2_norm_opt]: Optimizing L2 Normalize

lib/src/kernels/common/mli_krn_gru_cell.h, lib/src/kernels/common/mli_krn_lstm_cell.h, lib/src/kernels/transform/mli_krn_sigm_fx.cc, lib/src/kernels/transform/mli_krn_tanh_fx.cc
[sigm and tanh] update for in-place tensor; 
RID: 1226075
ML_lib_test_nsim/1878/ : PASS
=> [LSTM/GRU Cell opt] remove auxiliary tensors

lib/src/bricks/impl/mli_krn_dotprod_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h
RID: #1226336
ML_lib_test_nsim/1928:PASS
=> Optimize depthwise generic case

lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h, lib/src/pal/vdsp/mli_math.h
RID: #1226196
ML_lib_test_nsim/1935:PASS
=> Fix eltwise round overflow

lib/src/pal/vdsp/mli_math.h
=> Fix intra sum for acc_len == 8

lib/src/pal/dsp/mli_math.h, lib/src/private/mli_prv_tensor.h
RID:1229291
ML_lib_test_nsim/1972:PASS
=> Fix relu max min

lib/src/kernels/common/mli_krn_gru_cell.h, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc
RID: #1227944
ML_lib_test_nsim/1979:PASS
=> increase gru intermediate tensors quantization range

lib/src/kernels/common/impl/mli_krn_gru_cell_ref.h, lib/src/kernels/common/impl/mli_krn_gru_cell_vdsp.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_ref.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h, lib/src/kernels/common/mli_krn_gru_cell.h, lib/src/kernels/common/mli_krn_gru_cell_decl.h, lib/src/kernels/common/mli_krn_lstm_cell.h, lib/src/kernels/common/mli_krn_lstm_cell_decl.h, lib/src/private/mli_prv_tensor.h
Replace the sigma / tanh function call with a direct activation function call.
RID:1229889
ML_lib_test_nsim/2010/ : PASS
=> [LSTM/GRU Cell opt] Separate ref and opt versions. 

include/mli_types.h
RID: #1232248
ML_lib_test_nsim/2011:PASS
=> remove void_p field from mli_data_container union

lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/kernels/common/impl/mli_krn_fully_connected_ref.h, lib/src/kernels/common/impl/mli_krn_fully_connected_vdsp.h, lib/src/kernels/common/mli_krn_fully_connected_decl.h
RID: #1232732
ML_lib_test_nsim/2017:PASS
=> extra unroll for fully_connected and rnn sa8

lib/src/bricks/impl/mli_krn_dotprod_vdsp.h, lib/src/bricks/mli_krn_dotprod_decl.h, lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h
RID:1232730
ML_lib_test_nsim/2020:PASS
=> fix conv2d

lib/src/kernels/transform/impl/mli_krn_leaky_relu_ref.h, lib/src/kernels/transform/impl/mli_krn_leaky_relu_vdsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h, lib/src/kernels/transform/mli_krn_prelu.h, lib/src/kernels/transform/mli_krn_prelu_decl.h, user_tests/tests/mli_krn_leaky_relu/tests_mli_krn_leaky_relu.cc, user_tests/tests/mli_krn_prelu/tests_mli_krn_prelu.cc
RID:1232418
ML_lib_test_nsim/2019:PASS
=> use mlu_hi for leaky/prelu sa8

lib/src/kernels/common/impl/mli_krn_gru_cell_vdsp.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h, lib/src/kernels/transform/mli_krn_sigm_fx.cc, lib/src/kernels/transform/mli_krn_tanh_fx.cc, lib/src/private/mli_prv_activation_lut.h
Replace constants with defines. [sigm/tanh] Replace constants with defines.
RID:1232961
ML_lib_test_nsim/2048/ : PASS
=> [lstm_gru_opt] Combine of activation function calls. 

lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h
RID:1235026
ML_lib_test_nsim/2062:PASS
=> fix conv2d K1x1

lib/src/kernels/common/impl/mli_krn_gru_cell_vdsp.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h, lib/src/private/mli_prv_tensor.h
function to speed up activation functions.
RID:1236789
ML_lib_test_nsim/2107/ : PASS
=> [LSTM/GRU Cell opt] unroll the loops of mli_prv_get_generic_tensor 

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h
RID: 1236626
ML_lib_test_nsim/2093: PASSED
=> Add checking scalar options before getting data ptr

lib/src/bricks/impl/mli_prv_quant_dsp.h
RID:1237119
ML_lib_test_nsim/2103:PASS
=> add not FULL_ACCU to dw_dsp

lib/src/kernels/transform/impl/mli_krn_leaky_relu_dsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_dsp.h, lib/src/pal/dsp/mli_prv_load_store.h
RID:1237116
ML_lib_test_nsim/2101:PASS
=> fix relu_fx8 dsp version

lib/src/kernels/convolution/impl/mli_krn_group_conv2d_ref.h
RID:1235318
ML_lib_test_nsim/2077:PASS
=> code size optimizations group conv

lib/src/kernels/transform/impl/mli_krn_l2_normalize_vdsp.h
RID:1236465
ML_lib_test_nsim/2076:PASS
=> enable swp in L2_normalize

lib/src/bricks/impl/mli_prv_quant_ref.h
RID:1238606
ML_lib_test_nsim/2142:PASS
=> update bias_additive in ref

lib/src/move/impl/mli_mov_ref.h, lib/src/move/impl/mli_mov_vdsp.h, lib/src/move/mli_mov_api.cc, lib/src/move/mli_mov_decl.h
RID:1238683
ML_lib_test_nsim/2140:PASS
=> mli_mov code size reductions

lib/src/kernels/convolution/mli_krn_conv2d_hwcn.cc, lib/src/kernels/convolution/mli_krn_depthwise_conv2d_hwcn.cc, lib/src/kernels/convolution/mli_krn_group_conv2d_hwcn.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_sa8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_sa8.cc, lib/src/private/mli_check.h, lib/src/private/src/mli_check.cc
RID: #1235522
MLI_lib_test_nsim/2169:PASSED
=> [mli_check] Fixes of mli_check functions and kernel specializations.

examples/example_har_smartphone/README.md, examples/example_har_smartphone/har_smartphone_constants.h, examples/example_har_smartphone/har_smartphone_model_fx.c
and reduce codesize requirements for FX data type
RID: #1240601
MLI_lib_test_nsim/2175:PASSED
=> [EXAMPLE][HAR] Fix VPX platform run 

lib/src/bricks/impl/mli_prv_lut_ref.h, lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h
RID:1240723
ML_lib_test_nsim/2182:PASS
=> clip the shift for activations

doc/documents/mli_kernels/div_argmax.rst
RID: #1236641
MLI_lib_test_nsim/2217:PASSED
=> [docs] Updated argmax documentation.

lib/src/bricks/impl/mli_krn_rnn_dense_op_vdsp.h, lib/src/kernels/common/impl/mli_krn_gru_cell_ref.h, lib/src/kernels/common/impl/mli_krn_gru_cell_vdsp.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/private/mli_prv_tensor.h, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc
RID: #1233104
MLI_lib_test_nsim/2163:PASSED
=> improve GRU accuracy and fix bit-exactness

lib/src/move/impl/mli_mov_ref.h, lib/src/move/impl/mli_mov_vdsp.h, lib/src/move/mli_mov_api.cc, lib/src/move/mli_mov_decl.h, lib/src/private/src/mli_check.cc
RID: #1239998
ML_lib_test_nsim/2268:PASS
=> fix mov bugs and operate on quantization axis

lib/src/kernels/transform/impl/mli_krn_l2_normalize_vdsp.h
RID:1245813
ML_lib_test_nsim/2278:PASS
=> fix vectorized version of l2_normalize

lib/mli_lib.cmake, lib/src/bricks/impl/mli_krn_dotprod_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_convolution_vdsp.h, lib/src/kernels/convolution/impl/mli_krn_group_conv2d_vdsp.h, lib/src/kernels/diverse/impl/mli_krn_permute_vdsp.h, lib/src/kernels/transform/impl/mli_krn_l2_normalize_ref.h, lib/src/move/impl/mli_mov_ref.h, lib/src/move/impl/mli_mov_vdsp.h, lib/src/move/mli_mov_api.cc, lib/src/move/mli_mov_decl.h, lib/src/private/src/mli_check.cc
[Changes]
- Enable -Wsign-compare for ARC CLANG.
=> [Wsign-compare]

lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h
RID:1247034
ML_lib_test_nsim/2288:PASS
=> normalize in scale in eltwise_max/min

lib/src/move/impl/mli_mov_vdsp.h, lib/src/move/mli_mov_api.cc, lib/src/private/src/mli_check.cc
[Change]
- update mov cfg->size behaviour according to spec
- update mov checkers
- fix small bug
=> [mov fix] update cfg->size behaviour according to spec, small updates

include/mli_types.h, user_tests/tests/mli_krn_conv2d/vectors_mli_krn_conv2d.inc, user_tests/tests/mli_krn_depthwise_conv/vectors_mli_krn_depthwise_conv.inc, user_tests/tests/mli_krn_fully_connected/vectors_mli_krn_fully_connected.inc, user_tests/tests/mli_krn_group_conv2d/vectors_mli_krn_group_conv2d.inc, user_tests/tests/mli_krn_relu/tests_mli_krn_relu.cc, user_tests/tests/mli_krn_transpose_conv2d/vectors_mli_krn_transpose_conv2d.inc
Reverts foss-for-synopsys-dwc-arc-processors/embarc_mli#401
=> Revert "update relu cfg struct with min/max values"

lib/src/bricks/impl/mli_krn_rnn_dense_op_ref.h, lib/src/bricks/impl/mli_krn_rnn_dense_op_vdsp.h, lib/src/kernels/common/impl/mli_krn_gru_cell_ref.h, lib/src/kernels/common/impl/mli_krn_gru_cell_vdsp.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_ref.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h
MLI_lib_test_nsim:/2310:/PASSED
RID: #1249182
=> fix lstm and gru mem stride

lib/src/bricks/impl/mli_krn_reduce_max2d_vdsp.h, lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/kernels/common/mli_krn_fully_connected.cc, lib/src/kernels/convolution/mli_krn_depthwise_conv2d_hwcn.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_avepool_hwc_sa8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx16.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_fx8.cc, lib/src/kernels/pooling/mli_krn_maxpool_hwc_sa8.cc, lib/src/pal/vdsp/arc_vector_ext.h, lib/src/private/mli_prv_layout.h
RID:1251288
ML_lib_test_nsim/2317:PASS
=> cleanup dead code

lib/src/pal/mli_mem_info.h, lib/src/private/src/mli_check.cc
RID:1248904
ML_lib_test_nsim/2327:PASS
=> fix memory checks

lib/src/private/src/mli_check.cc
RID:1251473
ML_lib_test_nsim/2330:PASS
=> mem_check should be after null ptr checker

lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h, lib/src/helpers/src/impl/mli_hlp_convert_tensor_vdsp.h, lib/src/helpers/src/mli_helpers.cc, lib/src/helpers/src/mli_hlp_convert_tensor_decl.h, lib/src/pal/vdsp/mli_prv_load_store.h
RID: 1251424
ML_lib_test_nsim/2335/: PASS
=> Convert vdsp Opt

examples/auxiliary/examples_aux.c, lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h, lib/src/kernels/common/impl/mli_krn_fully_connected_ref.h, lib/src/kernels/convolution/impl/mli_krn_group_conv2d_ref.h, lib/src/kernels/convolution/impl/mli_krn_transpose_conv_ref.h, lib/src/kernels/diverse/impl/mli_krn_argmax_ref.h, lib/src/kernels/diverse/impl/mli_krn_permute_ref.h, lib/src/kernels/eltwise/impl/mli_krn_eltwise_ref.h, lib/src/kernels/pooling/mli_krn_pool_hwc.h, lib/src/kernels/transform/impl/mli_krn_l2_normalize_ref.h, lib/src/kernels/transform/impl/mli_krn_leaky_relu_ref.h, lib/src/kernels/transform/impl/mli_krn_prelu_ref.h, lib/src/kernels/transform/impl/mli_krn_relu_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h, lib/src/kernels/transform/mli_krn_sigm_fx.cc, lib/src/kernels/transform/mli_krn_tanh_fx.cc, lib/src/private/mli_prv_layout.h, lib/src/private/mli_prv_tensor.h, user_tests/tests/mli_krn_permute/tests_mli_krn_permute.cc
RID: 1251426
ML_lib_test_nsim/2329/: PASS
=> don't set output shape anymore

lib/src/kernels/transform/impl/mli_krn_leaky_relu_ref.h, lib/src/kernels/transform/impl/mli_krn_leaky_relu_vdsp.h, lib/src/kernels/transform/impl/mli_krn_prelu_vdsp.h
RID:1253054
ML_lib_test_nsim/2344:PASS
=> clip the shift for leaky/prelu

doc/documents/mli_kernels/trans_leaky_relu.rst, doc/documents/mli_kernels/trans_param_relu.rst
=> [Docs] Param\Leaky relu: Quant params in FX version must be the same 

examples/tutorial_emnist_tflm/conversion_tutorial/model_conversion.ipynb
RID: #1253631
MLI_lib_test_nsim/2347:PASSED
=> Fixed EMNIST TFLM tutorial.

lib/src/private/src/mli_check.cc
RID:1253570
ML_lib_test_nsim/2355:PASS
=> fix checker for leaky/prelu

doc/documents/data_movement/data_movement.rst, doc/documents/mli_api_data/data_structures.rst, doc/documents/mli_kernels/conv_2d.rst, doc/documents/mli_kernels/conv_depthwise.rst, doc/documents/mli_kernels/conv_grp.rst, doc/documents/mli_kernels/conv_transp.rst, doc/documents/mli_kernels/div_argmax.rst, doc/documents/mli_kernels/div_permute.rst, doc/documents/mli_kernels/elemw_grp.rst, doc/documents/mli_kernels/pool_avg.rst, doc/documents/mli_kernels/pool_max.rst, doc/documents/mli_kernels/rec_fully_con.rst, doc/documents/mli_kernels/rec_gru.rst, doc/documents/mli_kernels/rec_lstm.rst, doc/documents/mli_kernels/trans_l2_norm.rst, doc/documents/mli_kernels/trans_leaky_relu.rst, doc/documents/mli_kernels/trans_lut.rst, doc/documents/mli_kernels/trans_param_relu.rst, doc/documents/mli_kernels/trans_relu.rst, doc/documents/mli_kernels/trans_sigmoid.rst, doc/documents/mli_kernels/trans_softmax.rst, doc/documents/mli_kernels/trans_tanh.rst, doc/documents/utility_functions/util_data_conv.rst
CCID: 1251206
ML_lib_test_nsim/2368: PASS
=> [DOCS] Grammar corrections

examples/auxiliary/examples_aux.c, examples/example_har_smartphone/CMakeLists.txt, examples/example_har_smartphone/README.md, examples/example_har_smartphone/har_smartphone_model.h, examples/example_har_smartphone/har_smartphone_model_fx.c, examples/example_har_smartphone/har_smartphone_model_sa.c, examples/example_har_smartphone/ml_api_har_smartphone_main.c
Bugfixes and slight rework to align with recent library changes
=> [Examples][HAR] Rework example to align with Lib changes

lib/src/private/mli_check.h, lib/src/private/src/mli_check.cc
RID:1254453
ML_lib_test_nsim/2375:PASS
=> fix mli_checker

lib/src/bricks/impl/mli_prv_quant_vdsp.h, lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h, lib/src/helpers/src/impl/mli_hlp_convert_tensor_vdsp.h
RID: #1253797
MLI_lib_test_nsim/2377:/PASSED
=> fix convert bit-exactness

doc/documents/index.rst, doc/documents/platform_specific/platform_hint_sum.rst, doc/documents/platform_specific/vpx.rst, doc/documents/utility_functions/util_data_conv.rst, doc/documents/utility_functions/util_help_func.rst
=> [DOCS] Platform Specific Chapter

doc/documents/mli_kernels/conv_2d.rst, doc/documents/mli_kernels/conv_depthwise.rst, doc/documents/mli_kernels/conv_grp.rst, doc/documents/mli_kernels/conv_transp.rst, doc/documents/mli_kernels/div_argmax.rst, doc/documents/mli_kernels/div_permute.rst, doc/documents/mli_kernels/elemw_grp.rst, doc/documents/mli_kernels/pool_avg.rst, doc/documents/mli_kernels/pool_max.rst, doc/documents/mli_kernels/rec_fully_con.rst, doc/documents/mli_kernels/rec_gru.rst, doc/documents/mli_kernels/rec_lstm.rst, doc/documents/mli_kernels/rec_rnn_dense.rst, doc/documents/mli_kernels/trans_l2_norm.rst, doc/documents/mli_kernels/trans_leaky_relu.rst, doc/documents/mli_kernels/trans_param_relu.rst, doc/documents/mli_kernels/trans_relu.rst, doc/documents/mli_kernels/trans_sigmoid.rst, doc/documents/mli_kernels/trans_softmax.rst, doc/documents/mli_kernels/trans_tanh.rst, doc/documents/platform_specific/platform_hint_sum.rst
+ minor fixes of maxpool and eltwise max/min
CCID: 1257022
=> [DOCS] Reference to the platform specific conditions in all kernels 

examples/auxiliary/examples_aux.c
=> [EXAMPLES] Use old convert function in postprocess 

lib/src/helpers/src/impl/mli_hlp_convert_tensor_ref.h
[Change]
- Without these cast, MSVC gives errors
=> [convert] float casts

lib/src/kernels/common/impl/mli_krn_lstm_cell_ref.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h, lib/src/pal/dsp/mli_math.h, user_tests/tests/mli_krn_gru_cell/tests_mli_krn_gru_cell.cc, user_tests/tests/mli_krn_lstm_cell/tests_mli_krn_lstm_cell.cc, user_tests/tests/mli_krn_rnn_dense/tests_mli_krn_rnn_dense.cc
RID: #1256439
MLI_lib_test_nsim:/2409:/PASSED
=> Increase LSTM accuracy

lib/src/kernels/common/impl/mli_krn_lstm_cell_ref.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h
RID:1258233
ML_lib_test_nsim/2418:PASS
=> kernel should not change the cell tensor shape

doc/documents/utility_functions/util_help_func.rst, user_tests/tests/mli_hlp_tensor_struct/tests_mli_hlp_tensor_struct.cc, user_tests/tests/mli_hlp_tensor_struct/vectors_mli_hlp_tensor_struct.inc
=> [User Tests] mli_hlp_create_subtesor tests

README.md, examples/example_face_detect/Makefile, examples/example_face_detect/README.md, examples/hello_world/CMakeLists.txt, examples/hello_world/README.md, examples/hello_world/make/Makefile
+apply other minor fixes for release
=> [Docs][Examples] Complement FD and HelloWorld Examples Readme

examples/auxiliary/examples_aux.c, examples/auxiliary/examples_aux.h, examples/example_cifar10_caffe/cifar10_coefficients_hwcn_small.c, examples/example_cifar10_caffe/cifar10_constants.h, examples/example_cifar10_caffe/cifar10_model_hwcn.c
RID:1262751
ML_lib_test_nsim/2462:PASS
=> fix debug mode assertion in cifar

lib/src/move/mli_mov_api.cc
RID: #1263955
MLI_lib_test_nsim:/2466:/PASSED
=> fix quantization axis for mov in case of nullptr

lib/src/bricks/impl/mli_krn_reduce_sum2d_vdsp.h
RID:1263968
ML_lib_test_nsim/2462:PASS
=> fix avepool in integer base

examples/tutorial_emnist_tflm/README.md
RID:1263344
ML_lib_test_nsim/2470:PASS
=> EMNIST TFLM Readme: Add clarification on the TFLM compatible environment

cmake/settings.cmake, examples/tutorial_emnist_tflm/CMakeLists.txt, include/api/mli_mov_api.h, include/mli_types.h
RID:1266107
ML_lib_test_nsim/2494:PASS
=> add missing large enum fields to prevent enum size optimizations

lib/src/bricks/impl/mli_prv_lut_dsp.h, lib/src/bricks/impl/mli_prv_lut_ref.h, lib/src/bricks/impl/mli_prv_lut_vdsp.h, lib/src/bricks/mli_prv_lut_decl.h, lib/src/kernels/transform/impl/mli_krn_softmax_dsp.h, lib/src/kernels/transform/impl/mli_krn_softmax_ref.h, lib/src/kernels/transform/impl/mli_krn_softmax_vdsp.h, lib/src/kernels/transform/mli_krn_softmax.h, lib/src/kernels/transform/mli_krn_softmax_decl.h, lib/src/kernels/transform/mli_krn_softmax_fx.cc, user_tests/tests/mli_krn_softmax/tests_mli_krn_softmax.cc
RID: 1265287
ML_lib_test_nsim/2485/ : PASS
=> [softmax_fix]: Fix Softmax FX16 Accuarcy Issue.

lib/src/kernels/common/impl/mli_krn_gru_cell_ref.h, lib/src/kernels/common/impl/mli_krn_gru_cell_vdsp.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_ref.h, lib/src/kernels/common/impl/mli_krn_lstm_cell_vdsp.h, lib/src/private/src/mli_check.cc
RID:1266959
ML_lib_test_nsim/2501:PASS
=> fix checker for transpose/lstm/gru/rnn and make gru and lstm set mem_stride

lib/src/move/mli_mov_api.cc, lib/src/private/src/mli_check.cc
RID:1267582
ML_lib_test_nsim/2512:PASS
=> fix move checker

include/api/mli_kernels_api.h, include/mli_types.h
RID:1269297
ML_lib_test_nsim/2514:PASS
=> remove non-unicode characters from source files

lib/src/private/src/mli_check.cc
RID:1268818
ML_lib_test_nsim/2515:PASS
=> fix permute checker function

lib/src/private/src/mli_check.cc
RID:1273005
ML_lib_test_nsim/2533:PASS
=> add out el_type and el_params checks for gru and lstm

doc/documents/conf.py, doc/documents/data_movement/data_movement.rst, doc/documents/mli_api_data/data_layouts.rst, doc/documents/mli_api_data/data_structures.rst, doc/documents/mli_api_data/error_codes.rst, doc/documents/mli_kernels/conv_2d.rst, doc/documents/mli_kernels/conv_depthwise.rst, doc/documents/mli_kernels/conv_grp.rst, doc/documents/mli_kernels/conv_transp.rst, doc/documents/mli_kernels/convolution_grp.rst, doc/documents/mli_kernels/div_argmax.rst, doc/documents/mli_kernels/mli_kernels.rst, doc/documents/mli_kernels/pool_avg.rst, doc/documents/mli_kernels/pool_max.rst, doc/documents/mli_kernels/pooling_grp.rst, doc/documents/mli_kernels/rec_fully_con.rst, doc/documents/mli_kernels/rec_fully_con_grp.rst, doc/documents/mli_kernels/rec_gru.rst, doc/documents/mli_kernels/rec_lstm.rst, doc/documents/mli_kernels/rec_rnn_dense.rst, doc/documents/mli_kernels/trans_l2_norm.rst, doc/documents/mli_kernels/trans_param_relu.rst, doc/documents/mli_kernels/trans_relu.rst, doc/documents/overview/overview.rst, doc/documents/platform_specific/vpx.rst, doc/documents/utility_functions/util_help_func.rst, doc/documents/whats_new/whats_new.rst
RID:1274225
ML_lib_test_nsim/2537:PASS
=> [Docs] Long tables, optional copyright and other minor fixes

lib/src/kernels/eltwise/impl/mli_krn_eltwise_vdsp.h
RID:1308580
ML_lib_test_nsim/2702:PASS
=> remove unroll factor table
